name: hyphy
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - hyphy=2.5.62=h0705fce_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - libcurl=8.8.0=hca28451_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libgomp=13.2.0=h77fa898_7
  - libnghttp2=1.58.0=h47da74e_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libzlib=1.3.1=h4ab18f5_1
  - mpi=1.0=openmpi
  - muscle=5.1=h4ac6f70_3
  - ncurses=6.5=h59595ed_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.3.1=h4ab18f5_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /ohta1/bianca.sacchi/miniconda3/envs/hyphy
